TEST/ApiConsumerApp/Models/UsersModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ApiConsumerApp.Models
{
    public class UsersModel
    {
        public int ID { get; set; }
        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Please enter name")]
        public string Name { get; set; }
        [Display(Name = "Contact Number")]
        [Required(ErrorMessage = "Please enter Cell No")]
        public int Cell { get; set; }
        [Required(ErrorMessage = "Please enter Email ID")]
        public string MailAddress { get; set; }
        public string City { get; set; }
    }
}

TEST/ApiConsumerApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApiConsumerApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TEST/ApiConsumerApp/Controllers/UsersMVCController.cs
using ApiConsumerApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ApiConsumerApp.Controllers
{
    public class UsersMVCController : Controller
    {
        public ActionResult ViewUsers()
        {
            IEnumerable<UsersModel> userlist;
            HttpResponseMessage response = HttpClientVariable.ApiClient.GetAsync("Users").Result;
            userlist = response.Content.ReadAsAsync<IEnumerable<UsersModel>>().Result;
            return View(userlist);
             
        }
        // GET: UsersMVC
        public ActionResult Index()
        {
            IEnumerable<UsersModel> userlist;
            HttpResponseMessage response = HttpClientVariable.ApiClient.GetAsync("Users").Result;
            userlist = response.Content.ReadAsAsync<IEnumerable<UsersModel>>().Result;
            return View(userlist);
        }

        public ActionResult CreateUser()
        {
            return View();
        }

       [HttpPost]
        public ActionResult CreateUser(UsersModel Model)
        {
            HttpResponseMessage response = HttpClientVariable.ApiClient.PostAsJsonAsync("Users", Model).Result;
            TempData["Saved"] = "Saved Successfully";
            return RedirectToAction("Index");
        }

        public ActionResult UpdateUser(long? id)
        {
            
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            HttpResponseMessage response = HttpClientVariable.ApiClient.GetAsync("Users/"+id.ToString()).Result;
            if (response == null)
                {
                    return HttpNotFound();
                }
                return View(response.Content.ReadAsAsync<UsersModel>().Result);
            
        }
        [HttpPost]
        public ActionResult UpdateUser(UsersModel model)
        {
            if (model == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HttpResponseMessage response = HttpClientVariable.ApiClient.PutAsJsonAsync("Users/" + model.ID,model).Result;
            TempData["Updated"] = "Update Successfully";
            return RedirectToAction("Index");

        }

        public ActionResult DeleteUser(long? id)
        {
            HttpResponseMessage response = HttpClientVariable.ApiClient.DeleteAsync("Users/" +id.ToString()).Result;
            TempData["Deleted"] = "Delete Successfully";
            return RedirectToAction("Index");
        }
    }
}

TEST/ApiConsumerApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TEST/ApiConsumerApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TEST/ApiConsumerApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TEST/ApiConsumerApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test App", "Index", "UsersMVC", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                 
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Test Application API</p>
        </footer>
    </div>
    <script src="~/Scripts/alertify.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TEST/ApiConsumerApp/Views/UsersMVC/CreateUser.cshtml
@model ApiConsumerApp.Models.UsersModel

@{
    ViewBag.Title = "CreateUser";
}

<h2>CreateUser</h2>


@using (Html.BeginForm(FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cell, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cell, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cell, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TEST/ApiConsumerApp/Views/UsersMVC/Index.cshtml
@model IEnumerable<ApiConsumerApp.Models.UsersModel>

@{
    ViewBag.Title = "Index";

}

<head>
    @*<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <!-- BOOTSTRAP STYLES-->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/assets/css/custom.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li class="text-center user-image-back">
                        <img src="~/assets/img/find_user.png" class="img-responsive" />

                    </li>
                    <li>
                        <a href="index.html"><i class="fa fa-desktop "></i>Dashboard</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-edit "></i>Users<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="/UsersMVC/ViewUsers">User Details</a>
                            </li>
                            <li>
                                <a href="#">User History</a>
                            </li>
                           
                        </ul>
                    </li>

                     
                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">
                    <div class="row">
                     
                        <div class="col-md-offset-2 col-md-8 col-md-offset-1"> 

                            <a href="/UsersMVC/CreateUser" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-plus"></span>Add User</a>
                            <br />
                            <hr />
                            <table class="table table-striped table-bordered table-hover">
                                <tr>
                                    <th>
                                        @Html.DisplayName("USERS")
                                    </th>

                                </tr>
                                @{ 
                                    if(Model == null)
                                    {
                                        @Html.Label("NO RECORD !!!")
                                    }
                                    else
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>

                                                <td>
                                                    <button class="btn btn-default">@item.Name.Substring(0, 2).ToUpper()</button>  @Html.Label(item.Name.ToUpper())
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                               

                            </table>
                        </div>
                    </div>
                    <!-- /. ROW  -->
                    <hr />

                    <!-- /. ROW  -->
                </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
</body>
 <!-- /. WRAPPER  -->
<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
<!-- JQUERY SCRIPTS -->
<script src="~/assets/js/jquery-1.10.2.js"></script>
<!-- BOOTSTRAP SCRIPTS -->
<script src="~/assets/js/bootstrap.min.js"></script>
<!-- METISMENU SCRIPTS -->
<script src="~/assets/js/jquery.metisMenu.js"></script>
<!-- CUSTOM SCRIPTS -->
<script src="~/assets/js/custom.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>


<script>
    $(function () {

        var successmessage = '@TempData["Saved"]';
        if (successmessage != "") {
            alertify.success(successmessage);
        }

    });

            $(function () {

        var successmessage = '@TempData["Updated"]';
        if (successmessage != "") {
            alertify.success(successmessage);
        }

    });

    function Delete(id) {
        alertify.confirm('CRUD Operations', 'Are you sure to Delete this Record!!', function () {
            window.location.href = '/UsersMVC/DeleteUser/' + id;
        }, null);
    }
</script>

TEST/ApiConsumerApp/Views/UsersMVC/UpdateUser.cshtml
@model ApiConsumerApp.Models.UsersModel

@{
    ViewBag.Title = "UpdateUser";
}

<h2>UpdateUser</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cell, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cell, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cell, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TEST/ApiConsumerApp/Views/UsersMVC/ViewUsers.cshtml
@model IEnumerable<ApiConsumerApp.Models.UsersModel>

@{
    ViewBag.Title = "ViewUsers";
}

<h2>ViewUsers</h2>

 
<table class="table table-striped">
    <thead class="table-heading">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cell)
            </th>
            <th>
                @Html.DisplayName("Email")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>

        </tr>
    </thead>
    @{
        if (Model == null)
        {
            @Html.Label("NO RECORD !!!")
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cell)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MailAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "UpdateUser", new { id = item.ID }, new { @class = "glyphicon glyphicon-pencil" })

                    </td>
                    <td>
                        @*@Html.ActionLink(" ", "DeleteUser", new { id = item.ID }, new { @class = "glyphicon glyphicon-trash" })*@
                        <a onclick="Delete(@item.ID)"><i class="glyphicon glyphicon-trash"></i></a>
                    </td>

                </tr>
            }
        }
    }

   
</table>

<script>
 
    function Delete(id) {
        alertify.confirm('CRUD Operations', 'Are you sure to Delete this Record!!', function () {
            window.location.href = '/UsersMVC/DeleteUser/' + id;
        }, null);
    }
</script>